### PR TITLE
feat(BalanceTeams): implement balance teams and fix the average item level calculation

### LINKED ISSUE #27: Teams should be balanced according to player level (and item level)
We are using

```
CFBG.Include.Avg.Ilvl.Enable = 1
```

but it does not seem to create balanced teams.

We started a 3 vs 3 BG at 10-19 where the teams were:

- TEAM A: 3 players at level 10, 11 and 12
- TEAM B: 2 players at level 13, 18 and 19 

so it was completely unbalanced xD

-------------

I think we need a new config, such as 

```
CFBG.BalancedTeams = 1
```

when enabled, teams should be balanced with levels AND by item level.
 
So that when a new player queues, it will end up with the team having the lowest character level (sum of all players).
If the level is the same, it will end up to the team having the lowest item level (sum of all players).

### PR DESCRIPTION
**Pull request by Helias**
I fixed the average item level calculation and implemented the feature (enabled by default now) BalanceTeams.

This feature chooses the next team of the plater that joins BG taking the team with the lower sum of players' levels.
If the players' levels of the teams are the same it calculates the avg item level.

close https://github.com/azerothcore/mod-cfbg/issues/27

### CODE REVIEW

File: src/CFBG.cpp [hunk 1]
```diff
@@ -72,6 +77,35 @@ uint32 CFBG::GetBGTeamAverageItemLevel(Battleground* bg, TeamId team)
...
+    if (!bg)
+    {
+        return 0;
+    }
+
+    uint32 PlayersCount = bg->GetPlayersCountByTeam(team);
+    if (!PlayersCount)
+    {
+        return 0;
+    }
```
Comment (FrancescoBorzi) [inline src/CFBG.cpp]: why do we need this block?

Comment (Helias) [reply src/CFBG.cpp]: avoid going forward with the execution if there are no players

Comment (FrancescoBorzi) [reply src/CFBG.cpp]: @Helias I don't get it: below you are initialising `sum` to 0, then there is a for loop, then you return `sum`. If there are no players, the for loop won't begin and you'll return 0 anyway. So back to my original question: why do we need this block (lines 87-91)?

File: src/CFBG.cpp [hunk 2]
```diff
@@ -72,6 +77,35 @@ uint32 CFBG::GetBGTeamAverageItemLevel(Battleground* bg, TeamId team)
...
+
+    uint32 Sum = 0;
```
Comment (FrancescoBorzi) [inline src/CFBG.cpp]: rename to `sum` please

File: src/CFBG.cpp (hunk 1 above)
Comment (Helias) [reply src/CFBG.cpp]: removed

File: src/CFBG.cpp (hunk 2 above)
Comment (Helias) [reply src/CFBG.cpp]: done

**Comment by Helias** [comment]
updated, improved code quality

**Comment by FrancescoBorzi** [comment]
@Helias have you tested it one more time after the recent edits?

**Comment by Helias** [comment]
yes

**Review by FrancescoBorzi — APPROVED** [review]
