### PR TITLE
fix(CFBG): Set proper hostile reactions towards Alterac Valley NPCs a…

### LINKED ISSUE #76: Alterac Valley - Horde/Alliance NPCs Unfriendly to Faction-Swapped Players
Original report: https://github.com/chromiecraft/chromiecraft/issues/1953

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

I'm horde, but got into BG as alliance, and when I joined, as alliance guards that were alliance were unfriendly to me.
WoWScrnShot_100321_102424

This is maybe logic as they're alliance faction and I'm still horde even tho I'm in grp as alliance.

Tester: installed CFBG and confirmed. This was with an orc character changed to human. The Ally NPCs didn't attack me, and I couldn't attack them either, but they did show as unfriendly.

WoWScrnShot_100421_150006
WoWScrnShot_100421_150157
WoWScrnShot_100421_150241
WoWScrnShot_100421_150337

Also checked with Allies swapped to Horde. This is a nelf swapped to tauren:
WoWScrnShot_100421_152611
WoWScrnShot_100421_152619

This NPC (Smith Rezgar) starts a couple of quests I think, so being unfriendly is more than just a cosmetic issue.

### Expected Blizzlike Behaviour

Crossfaction is non blizzlike so nothing better to expect.

### Source

_No response_

### Steps to reproduce the problem

1. Enter AV as crossfaction and see

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Nyeriah**
…ccording to player team

Closes https://github.com/azerothcore/mod-cfbg/issues/76

Correct faction-changed players being hostile to their own team npcs, also forces the opposite team NPCs to be hostile.

Tests performed:

https://user-images.githubusercontent.com/47818697/140624997-4fa6eb19-365d-4912-a4c0-a706f77bdc8e.mp4

- Leaving BG, relogging - effects are removed properly:

Skärmbild 2021-11-06 183225

### CODE REVIEW

File: src/CFBG.h [hunk 1]
```diff
@@ -47,6 +47,14 @@ enum FakeMorphs
 
 };
 
+enum AVData
+{
+    MAP_ALTERAC_VALLEY     = 30,
+
+    FACTION_AV_FROSTWOLF_CLAN  = 729,
+    FACTION_AV_STORMPIKE_GUARD = 730,
+};
```
Comment (Winfidonarleyan) [inline src/CFBG.h]: Just use `constexpr` for this

**Review by Winfidonarleyan — APPROVED** [review]

**Review by Winfidonarleyan — COMMENTED** [review]
The best

**Review by Winfidonarleyan — APPROVED** [review]
