### PR TITLE
fix: only handle the Queue Announcements either by Core or CFBG, not both

### LINKED ISSUE #58: BG queue 0/4
**CURRENT BEHAVIOUR:**

image

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Should never show an announcement when 0 players are queued

##### STEPS TO REPRODUCE THE PROBLEM:

set this conf in `worldserver.conf`:

```
Battleground.QueueAnnouncer.Limit.MinLevel = 30
Battleground.QueueAnnouncer.Limit.MinPlayers = 3
Battleground.QueueAnnouncer.SpamProtection.Delay = 60
```

enable the CFBG module and set this conf:

```
CFBG.Enable = 1
CFBG.BalancedTeams = 1
CFBG.Include.Avg.Ilvl.Enable = 1
CFBG.Players.Count.In.Group = 1
CFBG.EvenTeams.Enabled = 1
CFBG.EvenTeams.MaxPlayersThreshold = 7
```

1. Queue a BG with a 19
2. Leave
3. Queue again

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/0d699222de92185681f9a78822a0e5d9898294f4

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Closes #58

I believe the current system is wrong as it lets both the CFBG **and** the core handle announcements. Instead, it should be only one of them. This was resulting in bugs such as #58

Now I changed it to:

- only make the Core handle the queue announcements **IF** it is arena **OR** if the CFBG is disabled
- only make the CFBG handle the queue announcements otherwise

## Test performed:

- tested locally with 1 player and the bug #58 is gone
- tested both with`CFBG.Enable = 1` and `CFBG.Enable = 0`, both seems fine

## What needs to be tested:
- test BG queue announcer in general, possibly with more chars ( both with`CFBG.Enable = 1` and `CFBG.Enable = 0`)
- a quick check on arena queue announcements wouldn't be bad, so we make sure we don't break them ( both with`CFBG.Enable = 1` and `CFBG.Enable = 0`)
- check that there is no regression in the queue announcements, it would be nice a quick check the Limit feature recently added
- would be interesting to play with `Battleground.QueueAnnouncer.SpamProtection.Delay` too and see how it goes

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
cc @Winfidonarleyan @Sedatyf

File: src/CFBG.cpp [hunk 1]
```diff
@@ -776,10 +776,8 @@ void CFBG::UpdateForget(Player* player)
 }
 
 std::unordered_map<ObjectGuid, uint32> BGSpamProtectionCFBG;
-bool CFBG::SendMessageQueue(BattlegroundQueue* bgQueue, Battleground* bg, PvPDifficultyEntry const* bracketEntry, Player* leader)
+void CFBG::SendMessageQueue(BattlegroundQueue* bgQueue, Battleground* bg, PvPDifficultyEntry const* bracketEntry, Player* leader)
 {
-    if (!IsEnableSystem())
-        return false;
```
Comment (Winfidonarleyan) [inline src/CFBG.cpp]: del new line

Comment (FrancescoBorzi) [reply src/CFBG.cpp]: done

**Review by Winfidonarleyan — APPROVED** [review]
